@EmployeeAdminPortal_HostAddress = https://localhost:7286

GET {{EmployeeAdminPortal_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{EmployeeAdminPortal_HostAddress}}/weatherforecast

###

GET {{EmployeeAdminPortal_HostAddress}}/weatherforecast

###

GET {{EmployeeAdminPortal_HostAddress}}/api/employees

###
